[browser]
gatherUsageStats = false

[server]
enableXsrfProtection = false
enableWebsocketCompression = false

[runner]
enforceSerializableSessionState = false

[client]
showErrorDetails = true

[theme]
primaryColor = "#007bff"
backgroundColor = "#f8f9fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#333333"